### ISSUE TITLE
i'm getting error "Please verify that the package.json has a valid "main" entry"

### ISSUE THREAD

**Issue by Majoramari** [Solaris9/erela.js-spotify#1]
i'm getting this error
Error: Cannot find module '.\node_modules\erela.js-spotify\dist\index.js'. Please verify that the package.json has a valid "main" entry
i installed it using npm i Solaris9/erela.js-spotify 👍

**Comment by anishshobithps** [comment]
Its written in typescript , so you cannot install it directly , you need to build it and then use it.

**Comment by anishshobithps** [comment]
Now you can install the package from the `build` branch via `npm i Solaris9/erela.js-spotify#build`
