### ISSUE TITLE
Spotify regex does not support http

### ISSUE THREAD

**Issue by GuilhermeVieiraDev** [Solaris9/erela.js-spotify#10]
In the constant REGEX in the plugin.ts file, the regex does not support the spotify url with http, only https.
So my suggestion is to update the regex to this one.

> **/(?:https?:\/\/open\.spotify\.com\/|spotify:)(.+)(?:[\/:])([A-Za-z0-9]+)/**

**Comment by Strandxo** [comment]
I doubt this will ever be used but I suppose it's best to have it than not to.
