### ISSUE TITLE
Axios critical security vulnerability

### ISSUE THREAD

**Issue by FredTheNoob** [Solaris9/erela.js-spotify#12]
Upon installing this npm package I recieved this warning from npm:

![image](https://user-images.githubusercontent.com/43958385/108594037-da8e6680-7377-11eb-9dac-f75924743a49.png)

Should I worry about this?

**Comment by JonasSchiott** [comment]
I suppose we need to update to the latest Axios version. No, I doubt that will affect your experience. Issue is now closed.

 - If any further inquiries, join our [Discord server](https://discord.gg/menudocs)
