### ISSUE TITLE
Unable to pass options: spotify clientID and clientSecret

### ISSUE THREAD

**Issue by FredTheNoob** [Solaris9/erela.js-spotify#13]
I have my secret and ID saved in a string, but upon passing it I get an error:

![image](https://user-images.githubusercontent.com/43958385/108594689-ba60a680-737b-11eb-96ac-24db7dc8d419.png)

I have added the plugin like so:
![image](https://user-images.githubusercontent.com/43958385/108594681-b46ac580-737b-11eb-83b5-ca26840d4363.png)

**Comment by Solaris9** [comment]
It asks for "clientID" but you use "spotifyClientID", it also asks for a non-empty string but you pass the string constructor, please view the readme for example usage of initiating the plugin.

**Comment by FredTheNoob** [comment]
Oh that's weird. The variable apparently has to be explicitly called clientID and not spotifyClientID. That solved my issue at last
