### ISSUE TITLE
Sometimes gives this error

### ISSUE THREAD

**Issue by emirkabal** [Solaris9/erela.js-spotify#16]
`{ message: 'Request failed with status code 401', severity: 'COMMON' }`

**Comment by Strandxo** [comment]
Sorry for the very delayed response but here's a video explaining what a 401 error is and how to fix it. Realistically without the whole error stack I can ONLY assume that this is to do with your spotify credentials and that they invalidate sometimes or something along those lines. https://www.youtube.com/watch?v=5mm93gB6Hu0

**Comment by emirkabal** [comment]
Sorry for this issue, the issue was caused by my server network problem.
