### ISSUE TITLE
Spotify enhancement

### ISSUE THREAD

**Issue by Spiderjockey02** [Solaris9/erela.js-spotify#9]
Maybe add support for spotify URI. For example: spotify:track:2mj7x99sNUsVHPBRK51zlG

**Comment by JonasSchiott** [comment]
I don't think that's necessary as no one actually grabs that. What's your use case?

**Comment by Solaris9** [comment]
It already supports [that](https://github.com/MenuDocs/erela.js-spotify/blob/master/src/plugin.ts#13)
